version: "3.8"

services:
  # Django application
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - conf.env
    volumes:
      - ./:/app

